# Cloudflare Worker configuration for OpenFeature MCP Server
name = "openfeature-mcp-server"
main = "src/index.ts"
compatibility_date = "2025-06-28"
compatibility_flags = ["nodejs_compat"]

# Production route
[[routes]]
pattern = "mcp-openfeature.devcycle.com/*"
zone_name = "devcycle.com"

# Durable Objects configuration
[[migrations]]
new_sqlite_classes = ["OpenFeatureMCP"]
tag = "v1"

[[durable_objects.bindings]]
class_name = "OpenFeatureMCP"
name = "MCP_OBJECT"

# Environment variables
[vars]
# NODE_ENV = "production"

# Observability
[observability]
enabled = true

# Development configuration
[dev]
port = 8787
local_protocol = "http"
