#!/usr/bin/env node

/**
 * Script to bundle prompts into a TypeScript file for Cloudflare Workers
 * This allows us to include prompt content at build time since Workers don't have file system access
 * 
 * Usage:
 *   node scripts/build-prompts.js
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function getAvailableGuides() {
  try {
    const files = await fs.readdir(PROMPTS_DIR);
    return files
      .filter(file => file.endsWith('.md') && file !== 'README.md')
      .map(file => file.replace('.md', ''))
      .sort();
  } catch (error) {
    console.warn('⚠️  Could not read prompts directory, using empty list');
    return [];
  }
}

const PROMPTS_DIR = path.join(__dirname, '..', 'prompts');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'tools', 'promptsBundle.generated.ts');

async function readPromptFile(guide) {
  const fileName = `${guide}.md`;
  const filePath = path.join(PROMPTS_DIR, fileName);
  
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    return content;
  } catch (error) {
    console.warn(`⚠️  ${guide}: Local prompt file not found`);
    return null;
  }
}

async function buildPromptsBundle() {
  console.log('🔨 Building prompts bundle...');
  
  const availableGuides = await getAvailableGuides();
  const prompts = {};
  let loadedCount = 0;
  
  for (const guide of availableGuides) {
    const content = await readPromptFile(guide);
    if (content !== null) {
      prompts[guide] = content;
      loadedCount++;
      console.log(`✅ ${guide}: Bundled`);
    }
  }
  
  // Generate TypeScript file
  const guideKeys = Object.keys(prompts);
  const tsContent = `// AUTO-GENERATED FILE - Do not edit manually
// Generated by scripts/build-prompts.js

export const INSTALL_GUIDES = [
${guideKeys.map(key => `    '${key}',`).join('\n')}
] as const;

export const BUNDLED_PROMPTS: Record<typeof INSTALL_GUIDES[number], string> = {
${Object.entries(prompts)
  .map(([guide, content]) => `  "${guide}": ${JSON.stringify(content)},`)
  .join('\n')}
};
`;

  await fs.writeFile(OUTPUT_FILE, tsContent, 'utf-8');
  
  console.log('\n📊 Bundle Summary:');
  console.log(`   ✅ Bundled: ${loadedCount}`);
  console.log(`   📁 Available guides: ${availableGuides.length}`);
  console.log(`   📄 Output: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
  
  if (loadedCount > 0) {
    console.log(`\n🎉 Prompts bundle created successfully!`);
  } else {
    console.log(`\n⚠️  No prompts were bundled. Make sure prompts exist in the prompts/ directory.`);
  }
}

async function main() {
  try {
    await buildPromptsBundle();
  } catch (error) {
    console.error('❌ Error building prompts bundle:', error);
    process.exit(1);
  }
}

// Check if this is the main module (ES module equivalent of require.main === module)
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}

export { buildPromptsBundle };
