// AUTO-GENERATED FILE - Do not edit manually
// Generated by scripts/build-providers.js

import { z } from 'zod';
import { INSTALL_GUIDES } from './promptsBundle.generated.js';

export const PROVIDERS = [

] as const;

export type ProviderName = string;

export const providersSchema = z.array(z.string()).default([]);

export const PROVIDER_SUPPORT: Record<ProviderName | string, { docsUrl: string; supportedGuides: typeof INSTALL_GUIDES[number][] }> = {

};
